name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore Misbah.sln
    - name: Build
      run: dotnet build Misbah.sln --no-restore --configuration Release
    - name: Test and Generate Coverage
      run: ./coverage.ps1